StylesPath = .vale/styles
MinAlertLevel = suggestion
Vocab = Fleet

Packages = Google, proselint

[*]
BasedOnStyles = Vale, Google, proselint

# Disable noisy style checks that conflict with systems documentation
Google.Acronyms = NO
Google.Parens = NO
Google.WordListCase = NO
Google.Colons = NO
Google.Headings = suggestion
Google.Contractions = NO
Google.LyHyphens = NO
Google.Latin = warning
Google.Ellipses = NO
Google.Will = suggestion
Google.Units = suggestion
proselint.Typography = NO
proselint.Annotations = NO
Vale.Terms = NO
